/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Digital Atlas of Ancient Life (https://sketchfab.com/DigitalAtlasOfAncientLife)
license: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
source: https://sketchfab.com/3d-models/argopecten-gibbus-pri-50125-ae909c439e2c42d9a8cce8196513ec9d
title: Argopecten gibbus (PRI 50125)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/coquillage.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.25, 16.14, -2.98]} rotation={[2.8, -0.04, 0.03]}>
          <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
          <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
          <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
