/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Smoggybeard (https://sketchfab.com/Smoggybeard)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/solar-system-model-orrery-ca0a6f6971a94fcc8d47421342dc6f40
title: Solar System Model (Orrery)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  
  const { nodes, materials, animations } = useGLTF('/system.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group position={[0, 0.3, -0.3]} rotation={[-Math.PI, 0, 0]} scale={0.57}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group>
              <group>
                <group position={[0, -81.97, 0]}>
                  <group position={[0, 81.97, -0.92]}>
                    <group>
                      <primitive object={nodes._rootJoint} />
                      <skinnedMesh geometry={nodes.Object_29.geometry} material={materials.Orrery_Textures} skeleton={nodes.Object_29.skeleton} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/system.glb')
